version: "3.8"

services: 
  web:
    build: .
    container_name: web_node
    command: npm run dev
    restart: always
    image: "node:latest"
    volumes: 
      - ./:/user/app
    working_dir: /user/app
    ports:
      - 3000:3000
    depends_on:
      - database
  database:
    image: "postgres:latest"
    environment:
      - POSTGRES_USER:apiconsumer
      - POSTGRES_DB:apidb
      - POSTGRES_PASSWORD=postgres_pwd

    